[envs.default]
pre-install-commands = [
  "pip install -r requirements-testing.txt"
]

[envs.default.scripts]
sync = "pip install -r requirements-testing.txt"
test = "pytest --cov-config pyproject.toml {args:test}"
typing = "mypy {args:src test maya_submitter_plugin/plug-ins}"
style = [
  "ruff check {args:.}",
  "black --check --diff {args:.}",
]
fmt = [
  "black {args:.}",
  "style",
]
lint = [
  "style",
  "typing",
]
install = "python {root}/scripts/install_dev_submitter.py {args:}"

[[envs.all.matrix]]
python = ["3.8", "3.9", "3.10", "3.11"]

[envs.default.env-vars]
SKIP_BOOTSTRAP_TEST_RESOURCES="True"
MAYA_ENV_DIR="{root}/plugin_env"

[envs.codebuild.scripts]
build = "hatch build"

[envs.codebuild.env-vars]
SKIP_BOOTSTRAP_TEST_RESOURCES="True"

[envs.integ.scripts]
test = "pytest --no-cov {args:test/*/integ}"

[envs.e2e.scripts]
test = "pytest --no-cov {args:test/*/e2e}"

[envs.release]
detached = true

[envs.release.scripts]
deps = "pip install -r requirements-release.txt"
bump = "semantic-release -v --strict version --no-push --no-commit --no-tag --skip-build {args}"
version = "semantic-release -v --strict version --print {args}"
