//Maya ASCII 2023 scene
//Name: layers.ma
//Last modified: Wed, Aug 30, 2023 04:47:49 PM
//Codeset: 1252
file -rdi 1 -ns "scene_file_to_reference" -rfn "scene_file_to_referenceRN" -op
		 "VERS|2023|UVER|undef|MADE|undef|CHNG|Wed, Aug 30, 2023 02:59:28 PM|ICON|undef|INFO|undef|OBJN|21|INCL|undef(|LUNI|cm|TUNI|film|AUNI|deg|TDUR|141120000|"
		 -typ "mayaBinary" "C:/Users/markw/deadline-clients/deadline-cloud-for-maya/job_bundle_output_tests/layers/scene/scene_file_to_reference.mb";
file -r -ns "scene_file_to_reference" -dr 1 -rfn "scene_file_to_referenceRN" -op
		 "VERS|2023|UVER|undef|MADE|undef|CHNG|Wed, Aug 30, 2023 02:59:28 PM|ICON|undef|INFO|undef|OBJN|21|INCL|undef(|LUNI|cm|TUNI|film|AUNI|deg|TDUR|141120000|"
		 -typ "mayaBinary" "C:/Users/markw/deadline-clients/deadline-cloud-for-maya/job_bundle_output_tests/layers/scene/scene_file_to_reference.mb";
requires maya "2023";
requires "stereoCamera" "10.0";
requires -nodeType "aiOptions" -nodeType "aiAOVDriver" -nodeType "aiAOVFilter" "mtoa" "5.1.0";
requires -nodeType "simpleSelector" -nodeType "lightsCollectionSelector" -nodeType "renderSetupLayer"
		 -nodeType "renderSetup" -nodeType "collection" -nodeType "lightsCollection" -nodeType "lightsChildCollection"
		 -nodeType "renderSettingsCollection" -nodeType "renderSettingsChildCollection" -nodeType "group"
		 -nodeType "absOverride" -nodeType "absUniqueOverride" -nodeType "relUniqueOverride"
		 -nodeType "applyRelFloatOverride" -nodeType "lightItem" -nodeType "lightEditor" "renderSetup.py" "1.0";
currentUnit -l centimeter -a degree -t film;
fileInfo "application" "maya";
fileInfo "product" "Maya 2023";
fileInfo "version" "2023";
fileInfo "cutIdentifier" "202202161415-df43006fd3";
fileInfo "osv" "Windows 10 Enterprise v2009 (Build: 19045)";
fileInfo "UUID" "9E06D67E-49F5-29F0-738D-B3A384C6F85C";
createNode transform -s -n "persp";
	rename -uid "886E9A75-4AB1-F9CC-E6CA-5BAE988657DF";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 21.906426765228382 32.663948327822368 -25.363058509714108 ;
	setAttr ".r" -type "double3" -38.738352729599939 137.39999999999822 0 ;
createNode camera -s -n "perspShape" -p "persp";
	rename -uid "52451BBA-4B9E-EC6D-1FF1-A3AA4C5806B3";
	setAttr -k off ".v" no;
	setAttr -s 2 ".rlio";
	setAttr -s 2 ".rlio";
	setAttr ".fl" 34.999999999999993;
	setAttr ".coi" 49.727751094329562;
	setAttr ".imn" -type "string" "persp";
	setAttr ".den" -type "string" "persp_depth";
	setAttr ".man" -type "string" "persp_mask";
	setAttr ".hc" -type "string" "viewSet -p %camera";
createNode transform -s -n "top";
	rename -uid "09D2508A-4306-4FFD-93B0-518C775F0D39";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 1000.1 0 ;
	setAttr ".r" -type "double3" -90 0 0 ;
createNode camera -s -n "topShape" -p "top";
	rename -uid "98E222E8-4854-3213-54A0-E592EC1A8205";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "top";
	setAttr ".den" -type "string" "top_depth";
	setAttr ".man" -type "string" "top_mask";
	setAttr ".hc" -type "string" "viewSet -t %camera";
	setAttr ".o" yes;
	setAttr ".ai_translator" -type "string" "orthographic";
createNode transform -s -n "front";
	rename -uid "6CB90538-4D77-D6FF-0595-BB91C18A51D9";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 0 1000.1 ;
createNode camera -s -n "frontShape" -p "front";
	rename -uid "7202AD6E-4B3E-B2DA-2192-E9ABDEA90DDF";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "front";
	setAttr ".den" -type "string" "front_depth";
	setAttr ".man" -type "string" "front_mask";
	setAttr ".hc" -type "string" "viewSet -f %camera";
	setAttr ".o" yes;
	setAttr ".ai_translator" -type "string" "orthographic";
createNode transform -s -n "side";
	rename -uid "70E69647-4EAE-5267-6F16-72867F3ADADC";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 1000.1 0 0 ;
	setAttr ".r" -type "double3" 0 90 0 ;
createNode camera -s -n "sideShape" -p "side";
	rename -uid "60814ADB-4A35-E293-AD0A-58952E7DF79A";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "side";
	setAttr ".den" -type "string" "side_depth";
	setAttr ".man" -type "string" "side_mask";
	setAttr ".hc" -type "string" "viewSet -s %camera";
	setAttr ".o" yes;
	setAttr ".ai_translator" -type "string" "orthographic";
createNode transform -n "camera1";
	rename -uid "9E84DFE5-4809-F4F5-B0F5-D2A1AE1BA766";
	setAttr ".t" -type "double3" 6.3988238494422669 5.2938657853455418 11.956330716866518 ;
	setAttr ".r" -type "double3" 0 0 20.879834883615128 ;
createNode camera -n "cameraShape1" -p "camera1";
	rename -uid "1EB7192A-4FCF-F249-11F6-FAB7DB40006B";
	setAttr -k off ".v";
	setAttr -s 2 ".rlio";
	setAttr -s 2 ".rlio";
	setAttr ".cap" -type "double2" 1.41732 0.94488 ;
	setAttr ".ff" 0;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "camera1";
	setAttr ".den" -type "string" "camera1_depth";
	setAttr ".man" -type "string" "camera1_mask";
createNode transform -n "camera2";
	rename -uid "93231F8B-4927-7ED9-0C0F-DA927E4B77D7";
	setAttr ".t" -type "double3" 10.640626151199671 7.5257274641127374 7.27611891860961 ;
	setAttr ".r" -type "double3" -26.385076031128424 55.635463959382875 0 ;
createNode camera -n "cameraShape2" -p "camera2";
	rename -uid "F816D91E-496B-228A-90E3-17AE3150DCCE";
	setAttr -k off ".v";
	setAttr ".rnd" no;
	setAttr ".cap" -type "double2" 1.41732 0.94488 ;
	setAttr ".ff" 0;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "camera2";
	setAttr ".den" -type "string" "camera2_depth";
	setAttr ".man" -type "string" "camera2_mask";
createNode transform -n "camera3";
	rename -uid "A0770A77-4367-C524-B16D-9AB5590BAB6D";
	setAttr ".t" -type "double3" 12.036375328812237 10.832033084236206 -4.842796257356059 ;
	setAttr ".r" -type "double3" -39.858415612227091 111.91722744948443 0 ;
createNode camera -n "cameraShape3" -p "camera3";
	rename -uid "3A8A2D6E-41E9-155B-78E2-E0A2DC905FBF";
	setAttr -k off ".v";
	setAttr ".rnd" no;
	setAttr ".cap" -type "double2" 1.41732 0.94488 ;
	setAttr ".ff" 0;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "camera3";
	setAttr ".den" -type "string" "camera3_depth";
	setAttr ".man" -type "string" "camera3_mask";
createNode transform -n "pSphere1";
	rename -uid "EE03B3B9-4FF1-3F73-A479-EA98F4A5440D";
	setAttr ".t" -type "double3" 0 5.2522790731366253 0 ;
createNode mesh -n "pSphereShape1" -p "pSphere1";
	rename -uid "3CA7AF72-4B10-D0A3-DC1A-219D1C341540";
	setAttr -k off ".v";
	setAttr ".vir" yes;
	setAttr ".vif" yes;
	setAttr ".uvst[0].uvsn" -type "string" "map1";
	setAttr ".cuvs" -type "string" "map1";
	setAttr ".dcc" -type "string" "Ambient+Diffuse";
	setAttr ".covm[0]"  0 1 1;
	setAttr ".cdvm[0]"  0 1 1;
createNode transform -n "pointLight1";
	rename -uid "2A69167D-4893-C36C-E0E2-07B7F213E730";
	setAttr ".t" -type "double3" 0 17.9943557142164 0 ;
createNode pointLight -n "pointLightShape1" -p "pointLight1";
	rename -uid "B38EAF98-4D41-962B-EB79-31841EFE4D7B";
	setAttr -k off ".v";
	setAttr -s 4 ".rlio";
	setAttr -s 4 ".rlio";
	setAttr ".us" no;
createNode lightLinker -s -n "lightLinker1";
	rename -uid "C117399F-46A6-992D-D176-1A92E16C3ABC";
	setAttr -s 2 ".lnk";
	setAttr -s 2 ".slnk";
createNode shapeEditorManager -n "shapeEditorManager";
	rename -uid "F084C3C3-4F6F-A17D-039C-05846F5657D9";
createNode poseInterpolatorManager -n "poseInterpolatorManager";
	rename -uid "66CA19FD-4C9A-36EF-F968-56AAC5A19650";
createNode displayLayerManager -n "layerManager";
	rename -uid "E2A9DC5C-4D9B-E9E9-2B25-CABE05690345";
createNode displayLayer -n "defaultLayer";
	rename -uid "07CE50F8-4073-2648-B942-D78A7A2B612C";
createNode renderLayerManager -n "renderLayerManager";
	rename -uid "DEAF6ACA-42CC-6F7B-C01E-A6AC14454883";
	setAttr ".crl" 5;
	setAttr -s 6 ".rlmi[1:5]"  1 2 3 4 5;
	setAttr -s 6 ".rlmi";
createNode renderLayer -n "defaultRenderLayer";
	rename -uid "5F81223C-4C71-1E4E-F11C-4DB627225CCD";
	setAttr ".g" yes;
	setAttr ".adjs[0].val" 0;
createNode aiOptions -s -n "defaultArnoldRenderOptions";
	rename -uid "6EBFD1EE-4AF3-6A01-F40D-2E8896F9ED86";
	setAttr ".version" -type "string" "5.1.0";
createNode aiAOVFilter -s -n "defaultArnoldFilter";
	rename -uid "19DDC798-46DC-CE52-B92C-88A1CF1F111E";
	setAttr ".ai_translator" -type "string" "gaussian";
createNode aiAOVDriver -s -n "defaultArnoldDriver";
	rename -uid "C1DD584F-48C9-9262-5EB1-0D87721582ED";
	setAttr ".ai_translator" -type "string" "exr";
createNode aiAOVDriver -s -n "defaultArnoldDisplayDriver";
	rename -uid "D9C35CA4-402D-D8DB-F5B5-6A95D5573881";
	setAttr ".output_mode" 0;
	setAttr ".ai_translator" -type "string" "maya";
createNode polySphere -n "polySphere1";
	rename -uid "BD3B123F-4A9B-B427-8037-B5B121FDE4B0";
createNode script -n "uiConfigurationScriptNode";
	rename -uid "DC28172C-4C6D-AAFF-03E6-619FB8C05ECE";
	setAttr ".b" -type "string" (
		"// Maya Mel UI Configuration File.\n//\n//  This script is machine generated.  Edit at your own risk.\n//\n//\n\nglobal string $gMainPane;\nif (`paneLayout -exists $gMainPane`) {\n\n\tglobal int $gUseScenePanelConfig;\n\tint    $useSceneConfig = $gUseScenePanelConfig;\n\tint    $nodeEditorPanelVisible = stringArrayContains(\"nodeEditorPanel1\", `getPanel -vis`);\n\tint    $nodeEditorWorkspaceControlOpen = (`workspaceControl -exists nodeEditorPanel1Window` && `workspaceControl -q -visible nodeEditorPanel1Window`);\n\tint    $menusOkayInPanels = `optionVar -q allowMenusInPanels`;\n\tint    $nVisPanes = `paneLayout -q -nvp $gMainPane`;\n\tint    $nPanes = 0;\n\tstring $editorName;\n\tstring $panelName;\n\tstring $itemFilterName;\n\tstring $panelConfig;\n\n\t//\n\t//  get current state of the UI\n\t//\n\tsceneUIReplacement -update $gMainPane;\n\n\t$panelName = `sceneUIReplacement -getNextPanel \"modelPanel\" (localizedPanelLabel(\"Top View\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tmodelPanel -edit -l (localizedPanelLabel(\"Top View\")) -mbv $menusOkayInPanels  $panelName;\n"
		+ "\t\t$editorName = $panelName;\n        modelEditor -e \n            -camera \"|top\" \n            -useInteractiveMode 0\n            -displayLights \"default\" \n            -displayAppearance \"smoothShaded\" \n            -activeOnly 0\n            -ignorePanZoom 0\n            -wireframeOnShaded 0\n            -headsUpDisplay 1\n            -holdOuts 1\n            -selectionHiliteDisplay 1\n            -useDefaultMaterial 0\n            -bufferMode \"double\" \n            -twoSidedLighting 0\n            -backfaceCulling 0\n            -xray 0\n            -jointXray 0\n            -activeComponentsXray 0\n            -displayTextures 0\n            -smoothWireframe 0\n            -lineWidth 1\n            -textureAnisotropic 0\n            -textureHilight 1\n            -textureSampling 2\n            -textureDisplay \"modulate\" \n            -textureMaxSize 32768\n            -fogging 0\n            -fogSource \"fragment\" \n            -fogMode \"linear\" \n            -fogStart 0\n            -fogEnd 100\n            -fogDensity 0.1\n            -fogColor 0.5 0.5 0.5 1 \n"
		+ "            -depthOfFieldPreview 1\n            -maxConstantTransparency 1\n            -rendererName \"vp2Renderer\" \n            -objectFilterShowInHUD 1\n            -isFiltered 0\n            -colorResolution 256 256 \n            -bumpResolution 512 512 \n            -textureCompression 0\n            -transparencyAlgorithm \"frontAndBackCull\" \n            -transpInShadows 0\n            -cullingOverride \"none\" \n            -lowQualityLighting 0\n            -maximumNumHardwareLights 1\n            -occlusionCulling 0\n            -shadingModel 0\n            -useBaseRenderer 0\n            -useReducedRenderer 0\n            -smallObjectCulling 0\n            -smallObjectThreshold -1 \n            -interactiveDisableShadows 0\n            -interactiveBackFaceCull 0\n            -sortTransparent 1\n            -controllers 1\n            -nurbsCurves 1\n            -nurbsSurfaces 1\n            -polymeshes 1\n            -subdivSurfaces 1\n            -planes 1\n            -lights 1\n            -cameras 1\n            -controlVertices 1\n"
		+ "            -hulls 1\n            -grid 1\n            -imagePlane 1\n            -joints 1\n            -ikHandles 1\n            -deformers 1\n            -dynamics 1\n            -particleInstancers 1\n            -fluids 1\n            -hairSystems 1\n            -follicles 1\n            -nCloths 1\n            -nParticles 1\n            -nRigids 1\n            -dynamicConstraints 1\n            -locators 1\n            -manipulators 1\n            -pluginShapes 1\n            -dimensions 1\n            -handles 1\n            -pivots 1\n            -textures 1\n            -strokes 1\n            -motionTrails 1\n            -clipGhosts 1\n            -greasePencils 0\n            -shadows 0\n            -captureSequenceNumber -1\n            -width 1\n            -height 1\n            -sceneRenderFilter 0\n            $editorName;\n        modelEditor -e -viewSelected 0 $editorName;\n        modelEditor -e \n            -pluginObjects \"gpuCacheDisplayFilter\" 1 \n            $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n"
		+ "\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextPanel \"modelPanel\" (localizedPanelLabel(\"Side View\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tmodelPanel -edit -l (localizedPanelLabel(\"Side View\")) -mbv $menusOkayInPanels  $panelName;\n\t\t$editorName = $panelName;\n        modelEditor -e \n            -camera \"|side\" \n            -useInteractiveMode 0\n            -displayLights \"default\" \n            -displayAppearance \"smoothShaded\" \n            -activeOnly 0\n            -ignorePanZoom 0\n            -wireframeOnShaded 0\n            -headsUpDisplay 1\n            -holdOuts 1\n            -selectionHiliteDisplay 1\n            -useDefaultMaterial 0\n            -bufferMode \"double\" \n            -twoSidedLighting 0\n            -backfaceCulling 0\n            -xray 0\n            -jointXray 0\n            -activeComponentsXray 0\n            -displayTextures 0\n            -smoothWireframe 0\n            -lineWidth 1\n            -textureAnisotropic 0\n            -textureHilight 1\n            -textureSampling 2\n"
		+ "            -textureDisplay \"modulate\" \n            -textureMaxSize 32768\n            -fogging 0\n            -fogSource \"fragment\" \n            -fogMode \"linear\" \n            -fogStart 0\n            -fogEnd 100\n            -fogDensity 0.1\n            -fogColor 0.5 0.5 0.5 1 \n            -depthOfFieldPreview 1\n            -maxConstantTransparency 1\n            -rendererName \"vp2Renderer\" \n            -objectFilterShowInHUD 1\n            -isFiltered 0\n            -colorResolution 256 256 \n            -bumpResolution 512 512 \n            -textureCompression 0\n            -transparencyAlgorithm \"frontAndBackCull\" \n            -transpInShadows 0\n            -cullingOverride \"none\" \n            -lowQualityLighting 0\n            -maximumNumHardwareLights 1\n            -occlusionCulling 0\n            -shadingModel 0\n            -useBaseRenderer 0\n            -useReducedRenderer 0\n            -smallObjectCulling 0\n            -smallObjectThreshold -1 \n            -interactiveDisableShadows 0\n            -interactiveBackFaceCull 0\n"
		+ "            -sortTransparent 1\n            -controllers 1\n            -nurbsCurves 1\n            -nurbsSurfaces 1\n            -polymeshes 1\n            -subdivSurfaces 1\n            -planes 1\n            -lights 1\n            -cameras 1\n            -controlVertices 1\n            -hulls 1\n            -grid 1\n            -imagePlane 1\n            -joints 1\n            -ikHandles 1\n            -deformers 1\n            -dynamics 1\n            -particleInstancers 1\n            -fluids 1\n            -hairSystems 1\n            -follicles 1\n            -nCloths 1\n            -nParticles 1\n            -nRigids 1\n            -dynamicConstraints 1\n            -locators 1\n            -manipulators 1\n            -pluginShapes 1\n            -dimensions 1\n            -handles 1\n            -pivots 1\n            -textures 1\n            -strokes 1\n            -motionTrails 1\n            -clipGhosts 1\n            -greasePencils 0\n            -shadows 0\n            -captureSequenceNumber -1\n            -width 1\n            -height 1\n"
		+ "            -sceneRenderFilter 0\n            $editorName;\n        modelEditor -e -viewSelected 0 $editorName;\n        modelEditor -e \n            -pluginObjects \"gpuCacheDisplayFilter\" 1 \n            $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextPanel \"modelPanel\" (localizedPanelLabel(\"Front View\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tmodelPanel -edit -l (localizedPanelLabel(\"Front View\")) -mbv $menusOkayInPanels  $panelName;\n\t\t$editorName = $panelName;\n        modelEditor -e \n            -camera \"|front\" \n            -useInteractiveMode 0\n            -displayLights \"default\" \n            -displayAppearance \"smoothShaded\" \n            -activeOnly 0\n            -ignorePanZoom 0\n            -wireframeOnShaded 0\n            -headsUpDisplay 1\n            -holdOuts 1\n            -selectionHiliteDisplay 1\n            -useDefaultMaterial 0\n            -bufferMode \"double\" \n            -twoSidedLighting 0\n            -backfaceCulling 0\n"
		+ "            -xray 0\n            -jointXray 0\n            -activeComponentsXray 0\n            -displayTextures 0\n            -smoothWireframe 0\n            -lineWidth 1\n            -textureAnisotropic 0\n            -textureHilight 1\n            -textureSampling 2\n            -textureDisplay \"modulate\" \n            -textureMaxSize 32768\n            -fogging 0\n            -fogSource \"fragment\" \n            -fogMode \"linear\" \n            -fogStart 0\n            -fogEnd 100\n            -fogDensity 0.1\n            -fogColor 0.5 0.5 0.5 1 \n            -depthOfFieldPreview 1\n            -maxConstantTransparency 1\n            -rendererName \"vp2Renderer\" \n            -objectFilterShowInHUD 1\n            -isFiltered 0\n            -colorResolution 256 256 \n            -bumpResolution 512 512 \n            -textureCompression 0\n            -transparencyAlgorithm \"frontAndBackCull\" \n            -transpInShadows 0\n            -cullingOverride \"none\" \n            -lowQualityLighting 0\n            -maximumNumHardwareLights 1\n            -occlusionCulling 0\n"
		+ "            -shadingModel 0\n            -useBaseRenderer 0\n            -useReducedRenderer 0\n            -smallObjectCulling 0\n            -smallObjectThreshold -1 \n            -interactiveDisableShadows 0\n            -interactiveBackFaceCull 0\n            -sortTransparent 1\n            -controllers 1\n            -nurbsCurves 1\n            -nurbsSurfaces 1\n            -polymeshes 1\n            -subdivSurfaces 1\n            -planes 1\n            -lights 1\n            -cameras 1\n            -controlVertices 1\n            -hulls 1\n            -grid 1\n            -imagePlane 1\n            -joints 1\n            -ikHandles 1\n            -deformers 1\n            -dynamics 1\n            -particleInstancers 1\n            -fluids 1\n            -hairSystems 1\n            -follicles 1\n            -nCloths 1\n            -nParticles 1\n            -nRigids 1\n            -dynamicConstraints 1\n            -locators 1\n            -manipulators 1\n            -pluginShapes 1\n            -dimensions 1\n            -handles 1\n            -pivots 1\n"
		+ "            -textures 1\n            -strokes 1\n            -motionTrails 1\n            -clipGhosts 1\n            -greasePencils 0\n            -shadows 0\n            -captureSequenceNumber -1\n            -width 1\n            -height 1\n            -sceneRenderFilter 0\n            $editorName;\n        modelEditor -e -viewSelected 0 $editorName;\n        modelEditor -e \n            -pluginObjects \"gpuCacheDisplayFilter\" 1 \n            $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextPanel \"modelPanel\" (localizedPanelLabel(\"Persp View\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tmodelPanel -edit -l (localizedPanelLabel(\"Persp View\")) -mbv $menusOkayInPanels  $panelName;\n\t\t$editorName = $panelName;\n        modelEditor -e \n            -camera \"|persp\" \n            -useInteractiveMode 0\n            -displayLights \"default\" \n            -displayAppearance \"smoothShaded\" \n            -activeOnly 0\n            -ignorePanZoom 0\n"
		+ "            -wireframeOnShaded 0\n            -headsUpDisplay 1\n            -holdOuts 1\n            -selectionHiliteDisplay 1\n            -useDefaultMaterial 0\n            -bufferMode \"double\" \n            -twoSidedLighting 0\n            -backfaceCulling 0\n            -xray 0\n            -jointXray 0\n            -activeComponentsXray 0\n            -displayTextures 0\n            -smoothWireframe 0\n            -lineWidth 1\n            -textureAnisotropic 0\n            -textureHilight 1\n            -textureSampling 2\n            -textureDisplay \"modulate\" \n            -textureMaxSize 32768\n            -fogging 0\n            -fogSource \"fragment\" \n            -fogMode \"linear\" \n            -fogStart 0\n            -fogEnd 100\n            -fogDensity 0.1\n            -fogColor 0.5 0.5 0.5 1 \n            -depthOfFieldPreview 1\n            -maxConstantTransparency 1\n            -rendererName \"vp2Renderer\" \n            -objectFilterShowInHUD 1\n            -isFiltered 0\n            -colorResolution 256 256 \n            -bumpResolution 512 512 \n"
		+ "            -textureCompression 0\n            -transparencyAlgorithm \"frontAndBackCull\" \n            -transpInShadows 0\n            -cullingOverride \"none\" \n            -lowQualityLighting 0\n            -maximumNumHardwareLights 1\n            -occlusionCulling 0\n            -shadingModel 0\n            -useBaseRenderer 0\n            -useReducedRenderer 0\n            -smallObjectCulling 0\n            -smallObjectThreshold -1 \n            -interactiveDisableShadows 0\n            -interactiveBackFaceCull 0\n            -sortTransparent 1\n            -controllers 1\n            -nurbsCurves 1\n            -nurbsSurfaces 1\n            -polymeshes 1\n            -subdivSurfaces 1\n            -planes 1\n            -lights 1\n            -cameras 1\n            -controlVertices 1\n            -hulls 1\n            -grid 1\n            -imagePlane 1\n            -joints 1\n            -ikHandles 1\n            -deformers 1\n            -dynamics 1\n            -particleInstancers 1\n            -fluids 1\n            -hairSystems 1\n            -follicles 1\n"
		+ "            -nCloths 1\n            -nParticles 1\n            -nRigids 1\n            -dynamicConstraints 1\n            -locators 1\n            -manipulators 1\n            -pluginShapes 1\n            -dimensions 1\n            -handles 1\n            -pivots 1\n            -textures 1\n            -strokes 1\n            -motionTrails 1\n            -clipGhosts 1\n            -greasePencils 0\n            -shadows 0\n            -captureSequenceNumber -1\n            -width 643\n            -height 648\n            -sceneRenderFilter 0\n            $editorName;\n        modelEditor -e -viewSelected 0 $editorName;\n        modelEditor -e \n            -pluginObjects \"gpuCacheDisplayFilter\" 1 \n            $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextPanel \"outlinerPanel\" (localizedPanelLabel(\"ToggledOutliner\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\toutlinerPanel -edit -l (localizedPanelLabel(\"ToggledOutliner\")) -mbv $menusOkayInPanels  $panelName;\n"
		+ "\t\t$editorName = $panelName;\n        outlinerEditor -e \n            -docTag \"isolOutln_fromSeln\" \n            -showShapes 0\n            -showAssignedMaterials 0\n            -showTimeEditor 1\n            -showReferenceNodes 1\n            -showReferenceMembers 1\n            -showAttributes 0\n            -showConnected 0\n            -showAnimCurvesOnly 0\n            -showMuteInfo 0\n            -organizeByLayer 1\n            -organizeByClip 1\n            -showAnimLayerWeight 1\n            -autoExpandLayers 1\n            -autoExpand 0\n            -showDagOnly 1\n            -showAssets 1\n            -showContainedOnly 1\n            -showPublishedAsConnected 0\n            -showParentContainers 0\n            -showContainerContents 1\n            -ignoreDagHierarchy 0\n            -expandConnections 0\n            -showUpstreamCurves 1\n            -showUnitlessCurves 1\n            -showCompounds 1\n            -showLeafs 1\n            -showNumericAttrsOnly 0\n            -highlightActive 1\n            -autoSelectNewObjects 0\n"
		+ "            -doNotSelectNewObjects 0\n            -dropIsParent 1\n            -transmitFilters 0\n            -setFilter \"defaultSetFilter\" \n            -showSetMembers 1\n            -allowMultiSelection 1\n            -alwaysToggleSelect 0\n            -directSelect 0\n            -isSet 0\n            -isSetMember 0\n            -displayMode \"DAG\" \n            -expandObjects 0\n            -setsIgnoreFilters 1\n            -containersIgnoreFilters 0\n            -editAttrName 0\n            -showAttrValues 0\n            -highlightSecondary 0\n            -showUVAttrsOnly 0\n            -showTextureNodesOnly 0\n            -attrAlphaOrder \"default\" \n            -animLayerFilterOptions \"allAffecting\" \n            -sortOrder \"none\" \n            -longNames 0\n            -niceNames 1\n            -showNamespace 1\n            -showPinIcons 0\n            -mapMotionTrails 0\n            -ignoreHiddenAttribute 0\n            -ignoreOutlinerColor 0\n            -renderFilterVisible 0\n            -renderFilterIndex 0\n            -selectionOrder \"chronological\" \n"
		+ "            -expandAttribute 0\n            $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextPanel \"outlinerPanel\" (localizedPanelLabel(\"Outliner\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\toutlinerPanel -edit -l (localizedPanelLabel(\"Outliner\")) -mbv $menusOkayInPanels  $panelName;\n\t\t$editorName = $panelName;\n        outlinerEditor -e \n            -showShapes 0\n            -showAssignedMaterials 0\n            -showTimeEditor 1\n            -showReferenceNodes 0\n            -showReferenceMembers 0\n            -showAttributes 0\n            -showConnected 0\n            -showAnimCurvesOnly 0\n            -showMuteInfo 0\n            -organizeByLayer 1\n            -organizeByClip 1\n            -showAnimLayerWeight 1\n            -autoExpandLayers 1\n            -autoExpand 0\n            -showDagOnly 1\n            -showAssets 1\n            -showContainedOnly 1\n            -showPublishedAsConnected 0\n            -showParentContainers 0\n"
		+ "            -showContainerContents 1\n            -ignoreDagHierarchy 0\n            -expandConnections 0\n            -showUpstreamCurves 1\n            -showUnitlessCurves 1\n            -showCompounds 1\n            -showLeafs 1\n            -showNumericAttrsOnly 0\n            -highlightActive 1\n            -autoSelectNewObjects 0\n            -doNotSelectNewObjects 0\n            -dropIsParent 1\n            -transmitFilters 0\n            -setFilter \"defaultSetFilter\" \n            -showSetMembers 1\n            -allowMultiSelection 1\n            -alwaysToggleSelect 0\n            -directSelect 0\n            -displayMode \"DAG\" \n            -expandObjects 0\n            -setsIgnoreFilters 1\n            -containersIgnoreFilters 0\n            -editAttrName 0\n            -showAttrValues 0\n            -highlightSecondary 0\n            -showUVAttrsOnly 0\n            -showTextureNodesOnly 0\n            -attrAlphaOrder \"default\" \n            -animLayerFilterOptions \"allAffecting\" \n            -sortOrder \"none\" \n            -longNames 0\n"
		+ "            -niceNames 1\n            -showNamespace 1\n            -showPinIcons 0\n            -mapMotionTrails 0\n            -ignoreHiddenAttribute 0\n            -ignoreOutlinerColor 0\n            -renderFilterVisible 0\n            $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"graphEditor\" (localizedPanelLabel(\"Graph Editor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Graph Editor\")) -mbv $menusOkayInPanels  $panelName;\n\n\t\t\t$editorName = ($panelName+\"OutlineEd\");\n            outlinerEditor -e \n                -showShapes 1\n                -showAssignedMaterials 0\n                -showTimeEditor 1\n                -showReferenceNodes 0\n                -showReferenceMembers 0\n                -showAttributes 1\n                -showConnected 1\n                -showAnimCurvesOnly 1\n                -showMuteInfo 0\n                -organizeByLayer 1\n                -organizeByClip 1\n"
		+ "                -showAnimLayerWeight 1\n                -autoExpandLayers 1\n                -autoExpand 1\n                -showDagOnly 0\n                -showAssets 1\n                -showContainedOnly 0\n                -showPublishedAsConnected 0\n                -showParentContainers 0\n                -showContainerContents 0\n                -ignoreDagHierarchy 0\n                -expandConnections 1\n                -showUpstreamCurves 1\n                -showUnitlessCurves 1\n                -showCompounds 0\n                -showLeafs 1\n                -showNumericAttrsOnly 1\n                -highlightActive 0\n                -autoSelectNewObjects 1\n                -doNotSelectNewObjects 0\n                -dropIsParent 1\n                -transmitFilters 1\n                -setFilter \"0\" \n                -showSetMembers 0\n                -allowMultiSelection 1\n                -alwaysToggleSelect 0\n                -directSelect 0\n                -displayMode \"DAG\" \n                -expandObjects 0\n                -setsIgnoreFilters 1\n"
		+ "                -containersIgnoreFilters 0\n                -editAttrName 0\n                -showAttrValues 0\n                -highlightSecondary 0\n                -showUVAttrsOnly 0\n                -showTextureNodesOnly 0\n                -attrAlphaOrder \"default\" \n                -animLayerFilterOptions \"allAffecting\" \n                -sortOrder \"none\" \n                -longNames 0\n                -niceNames 1\n                -showNamespace 1\n                -showPinIcons 1\n                -mapMotionTrails 1\n                -ignoreHiddenAttribute 0\n                -ignoreOutlinerColor 0\n                -renderFilterVisible 0\n                $editorName;\n\n\t\t\t$editorName = ($panelName+\"GraphEd\");\n            animCurveEditor -e \n                -displayValues 0\n                -snapTime \"integer\" \n                -snapValue \"none\" \n                -showPlayRangeShades \"on\" \n                -lockPlayRangeShades \"off\" \n                -smoothness \"fine\" \n                -resultSamples 1\n                -resultScreenSamples 0\n"
		+ "                -resultUpdate \"delayed\" \n                -showUpstreamCurves 1\n                -keyMinScale 1\n                -stackedCurvesMin -1\n                -stackedCurvesMax 1\n                -stackedCurvesSpace 0.2\n                -preSelectionHighlight 0\n                -constrainDrag 0\n                -valueLinesToggle 1\n                -outliner \"graphEditor1OutlineEd\" \n                -highlightAffectedCurves 0\n                $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"dopeSheetPanel\" (localizedPanelLabel(\"Dope Sheet\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Dope Sheet\")) -mbv $menusOkayInPanels  $panelName;\n\n\t\t\t$editorName = ($panelName+\"OutlineEd\");\n            outlinerEditor -e \n                -showShapes 1\n                -showAssignedMaterials 0\n                -showTimeEditor 1\n                -showReferenceNodes 0\n                -showReferenceMembers 0\n"
		+ "                -showAttributes 1\n                -showConnected 1\n                -showAnimCurvesOnly 1\n                -showMuteInfo 0\n                -organizeByLayer 1\n                -organizeByClip 1\n                -showAnimLayerWeight 1\n                -autoExpandLayers 1\n                -autoExpand 0\n                -showDagOnly 0\n                -showAssets 1\n                -showContainedOnly 0\n                -showPublishedAsConnected 0\n                -showParentContainers 0\n                -showContainerContents 0\n                -ignoreDagHierarchy 0\n                -expandConnections 1\n                -showUpstreamCurves 1\n                -showUnitlessCurves 0\n                -showCompounds 1\n                -showLeafs 1\n                -showNumericAttrsOnly 1\n                -highlightActive 0\n                -autoSelectNewObjects 0\n                -doNotSelectNewObjects 1\n                -dropIsParent 1\n                -transmitFilters 0\n                -setFilter \"0\" \n                -showSetMembers 0\n"
		+ "                -allowMultiSelection 1\n                -alwaysToggleSelect 0\n                -directSelect 0\n                -displayMode \"DAG\" \n                -expandObjects 0\n                -setsIgnoreFilters 1\n                -containersIgnoreFilters 0\n                -editAttrName 0\n                -showAttrValues 0\n                -highlightSecondary 0\n                -showUVAttrsOnly 0\n                -showTextureNodesOnly 0\n                -attrAlphaOrder \"default\" \n                -animLayerFilterOptions \"allAffecting\" \n                -sortOrder \"none\" \n                -longNames 0\n                -niceNames 1\n                -showNamespace 1\n                -showPinIcons 0\n                -mapMotionTrails 1\n                -ignoreHiddenAttribute 0\n                -ignoreOutlinerColor 0\n                -renderFilterVisible 0\n                $editorName;\n\n\t\t\t$editorName = ($panelName+\"DopeSheetEd\");\n            dopeSheetEditor -e \n                -displayValues 0\n                -snapTime \"integer\" \n"
		+ "                -snapValue \"none\" \n                -outliner \"dopeSheetPanel1OutlineEd\" \n                -showSummary 1\n                -showScene 0\n                -hierarchyBelow 0\n                -showTicks 1\n                -selectionWindow 0 0 0 0 \n                $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"timeEditorPanel\" (localizedPanelLabel(\"Time Editor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Time Editor\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"clipEditorPanel\" (localizedPanelLabel(\"Trax Editor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Trax Editor\")) -mbv $menusOkayInPanels  $panelName;\n\n\t\t\t$editorName = clipEditorNameFromPanel($panelName);\n"
		+ "            clipEditor -e \n                -displayValues 0\n                -snapTime \"none\" \n                -snapValue \"none\" \n                -initialized 0\n                -manageSequencer 0 \n                $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"sequenceEditorPanel\" (localizedPanelLabel(\"Camera Sequencer\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Camera Sequencer\")) -mbv $menusOkayInPanels  $panelName;\n\n\t\t\t$editorName = sequenceEditorNameFromPanel($panelName);\n            clipEditor -e \n                -displayValues 0\n                -snapTime \"none\" \n                -snapValue \"none\" \n                -initialized 0\n                -manageSequencer 1 \n                $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"hyperGraphPanel\" (localizedPanelLabel(\"Hypergraph Hierarchy\")) `;\n"
		+ "\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Hypergraph Hierarchy\")) -mbv $menusOkayInPanels  $panelName;\n\n\t\t\t$editorName = ($panelName+\"HyperGraphEd\");\n            hyperGraph -e \n                -graphLayoutStyle \"hierarchicalLayout\" \n                -orientation \"horiz\" \n                -mergeConnections 0\n                -zoom 1\n                -animateTransition 0\n                -showRelationships 1\n                -showShapes 0\n                -showDeformers 0\n                -showExpressions 0\n                -showConstraints 0\n                -showConnectionFromSelected 0\n                -showConnectionToSelected 0\n                -showConstraintLabels 0\n                -showUnderworld 0\n                -showInvisible 0\n                -transitionFrames 1\n                -opaqueContainers 0\n                -freeform 0\n                -imagePosition 0 0 \n                -imageScale 1\n                -imageEnabled 0\n                -graphType \"DAG\" \n"
		+ "                -heatMapDisplay 0\n                -updateSelection 1\n                -updateNodeAdded 1\n                -useDrawOverrideColor 0\n                -limitGraphTraversal -1\n                -range 0 0 \n                -iconSize \"smallIcons\" \n                -showCachedConnections 0\n                $editorName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"hyperShadePanel\" (localizedPanelLabel(\"Hypershade\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Hypershade\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"visorPanel\" (localizedPanelLabel(\"Visor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Visor\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n"
		+ "\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"nodeEditorPanel\" (localizedPanelLabel(\"Node Editor\")) `;\n\tif ($nodeEditorPanelVisible || $nodeEditorWorkspaceControlOpen) {\n\t\tif (\"\" == $panelName) {\n\t\t\tif ($useSceneConfig) {\n\t\t\t\t$panelName = `scriptedPanel -unParent  -type \"nodeEditorPanel\" -l (localizedPanelLabel(\"Node Editor\")) -mbv $menusOkayInPanels `;\n\n\t\t\t$editorName = ($panelName+\"NodeEditorEd\");\n            nodeEditor -e \n                -allAttributes 0\n                -allNodes 0\n                -autoSizeNodes 1\n                -consistentNameSize 1\n                -createNodeCommand \"nodeEdCreateNodeCommand\" \n                -connectNodeOnCreation 0\n                -connectOnDrop 0\n                -copyConnectionsOnPaste 0\n                -connectionStyle \"bezier\" \n                -defaultPinnedState 0\n                -additiveGraphingMode 0\n                -connectedGraphingMode 1\n                -settingsChangedCallback \"nodeEdSyncControls\" \n                -traversalDepthLimit -1\n"
		+ "                -keyPressCommand \"nodeEdKeyPressCommand\" \n                -nodeTitleMode \"name\" \n                -gridSnap 0\n                -gridVisibility 1\n                -crosshairOnEdgeDragging 0\n                -popupMenuScript \"nodeEdBuildPanelMenus\" \n                -showNamespace 1\n                -showShapes 1\n                -showSGShapes 0\n                -showTransforms 1\n                -useAssets 1\n                -syncedSelection 1\n                -extendToShapes 1\n                -showUnitConversions 0\n                -editorMode \"default\" \n                -hasWatchpoint 0\n                $editorName;\n\t\t\t}\n\t\t} else {\n\t\t\t$label = `panel -q -label $panelName`;\n\t\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Node Editor\")) -mbv $menusOkayInPanels  $panelName;\n\n\t\t\t$editorName = ($panelName+\"NodeEditorEd\");\n            nodeEditor -e \n                -allAttributes 0\n                -allNodes 0\n                -autoSizeNodes 1\n                -consistentNameSize 1\n                -createNodeCommand \"nodeEdCreateNodeCommand\" \n"
		+ "                -connectNodeOnCreation 0\n                -connectOnDrop 0\n                -copyConnectionsOnPaste 0\n                -connectionStyle \"bezier\" \n                -defaultPinnedState 0\n                -additiveGraphingMode 0\n                -connectedGraphingMode 1\n                -settingsChangedCallback \"nodeEdSyncControls\" \n                -traversalDepthLimit -1\n                -keyPressCommand \"nodeEdKeyPressCommand\" \n                -nodeTitleMode \"name\" \n                -gridSnap 0\n                -gridVisibility 1\n                -crosshairOnEdgeDragging 0\n                -popupMenuScript \"nodeEdBuildPanelMenus\" \n                -showNamespace 1\n                -showShapes 1\n                -showSGShapes 0\n                -showTransforms 1\n                -useAssets 1\n                -syncedSelection 1\n                -extendToShapes 1\n                -showUnitConversions 0\n                -editorMode \"default\" \n                -hasWatchpoint 0\n                $editorName;\n\t\t\tif (!$useSceneConfig) {\n"
		+ "\t\t\t\tpanel -e -l $label $panelName;\n\t\t\t}\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"createNodePanel\" (localizedPanelLabel(\"Create Node\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Create Node\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"polyTexturePlacementPanel\" (localizedPanelLabel(\"UV Editor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"UV Editor\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"renderWindowPanel\" (localizedPanelLabel(\"Render View\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Render View\")) -mbv $menusOkayInPanels  $panelName;\n"
		+ "\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextPanel \"shapePanel\" (localizedPanelLabel(\"Shape Editor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tshapePanel -edit -l (localizedPanelLabel(\"Shape Editor\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextPanel \"posePanel\" (localizedPanelLabel(\"Pose Editor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tposePanel -edit -l (localizedPanelLabel(\"Pose Editor\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"dynRelEdPanel\" (localizedPanelLabel(\"Dynamic Relationships\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Dynamic Relationships\")) -mbv $menusOkayInPanels  $panelName;\n"
		+ "\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"relationshipPanel\" (localizedPanelLabel(\"Relationship Editor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Relationship Editor\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"referenceEditorPanel\" (localizedPanelLabel(\"Reference Editor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Reference Editor\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"dynPaintScriptedPanelType\" (localizedPanelLabel(\"Paint Effects\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Paint Effects\")) -mbv $menusOkayInPanels  $panelName;\n"
		+ "\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"scriptEditorPanel\" (localizedPanelLabel(\"Script Editor\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Script Editor\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"profilerPanel\" (localizedPanelLabel(\"Profiler Tool\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Profiler Tool\")) -mbv $menusOkayInPanels  $panelName;\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"contentBrowserPanel\" (localizedPanelLabel(\"Content Browser\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Content Browser\")) -mbv $menusOkayInPanels  $panelName;\n"
		+ "\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\t$panelName = `sceneUIReplacement -getNextScriptedPanel \"Stereo\" (localizedPanelLabel(\"Stereo\")) `;\n\tif (\"\" != $panelName) {\n\t\t$label = `panel -q -label $panelName`;\n\t\tscriptedPanel -edit -l (localizedPanelLabel(\"Stereo\")) -mbv $menusOkayInPanels  $panelName;\n{ string $editorName = ($panelName+\"Editor\");\n            stereoCameraView -e \n                -camera \"|persp\" \n                -useInteractiveMode 0\n                -displayLights \"default\" \n                -displayAppearance \"smoothShaded\" \n                -activeOnly 0\n                -ignorePanZoom 0\n                -wireframeOnShaded 0\n                -headsUpDisplay 1\n                -holdOuts 1\n                -selectionHiliteDisplay 1\n                -useDefaultMaterial 0\n                -bufferMode \"double\" \n                -twoSidedLighting 0\n                -backfaceCulling 0\n                -xray 0\n                -jointXray 0\n                -activeComponentsXray 0\n                -displayTextures 0\n"
		+ "                -smoothWireframe 0\n                -lineWidth 1\n                -textureAnisotropic 0\n                -textureHilight 1\n                -textureSampling 2\n                -textureDisplay \"modulate\" \n                -textureMaxSize 32768\n                -fogging 0\n                -fogSource \"fragment\" \n                -fogMode \"linear\" \n                -fogStart 0\n                -fogEnd 100\n                -fogDensity 0.1\n                -fogColor 0.5 0.5 0.5 1 \n                -depthOfFieldPreview 1\n                -maxConstantTransparency 1\n                -objectFilterShowInHUD 1\n                -isFiltered 0\n                -colorResolution 4 4 \n                -bumpResolution 4 4 \n                -textureCompression 0\n                -transparencyAlgorithm \"frontAndBackCull\" \n                -transpInShadows 0\n                -cullingOverride \"none\" \n                -lowQualityLighting 0\n                -maximumNumHardwareLights 0\n                -occlusionCulling 0\n                -shadingModel 0\n"
		+ "                -useBaseRenderer 0\n                -useReducedRenderer 0\n                -smallObjectCulling 0\n                -smallObjectThreshold -1 \n                -interactiveDisableShadows 0\n                -interactiveBackFaceCull 0\n                -sortTransparent 1\n                -controllers 1\n                -nurbsCurves 1\n                -nurbsSurfaces 1\n                -polymeshes 1\n                -subdivSurfaces 1\n                -planes 1\n                -lights 1\n                -cameras 1\n                -controlVertices 1\n                -hulls 1\n                -grid 1\n                -imagePlane 1\n                -joints 1\n                -ikHandles 1\n                -deformers 1\n                -dynamics 1\n                -particleInstancers 1\n                -fluids 1\n                -hairSystems 1\n                -follicles 1\n                -nCloths 1\n                -nParticles 1\n                -nRigids 1\n                -dynamicConstraints 1\n                -locators 1\n                -manipulators 1\n"
		+ "                -pluginShapes 1\n                -dimensions 1\n                -handles 1\n                -pivots 1\n                -textures 1\n                -strokes 1\n                -motionTrails 1\n                -clipGhosts 1\n                -greasePencils 0\n                -shadows 0\n                -captureSequenceNumber -1\n                -width 0\n                -height 0\n                -sceneRenderFilter 0\n                -displayMode \"centerEye\" \n                -viewColor 0 0 0 1 \n                -useCustomBackground 1\n                $editorName;\n            stereoCameraView -e -viewSelected 0 $editorName;\n            stereoCameraView -e \n                -pluginObjects \"gpuCacheDisplayFilter\" 1 \n                $editorName; };\n\t\tif (!$useSceneConfig) {\n\t\t\tpanel -e -l $label $panelName;\n\t\t}\n\t}\n\n\n\tif ($useSceneConfig) {\n        string $configName = `getPanel -cwl (localizedPanelLabel(\"Current Layout\"))`;\n        if (\"\" != $configName) {\n\t\t\tpanelConfiguration -edit -label (localizedPanelLabel(\"Current Layout\")) \n"
		+ "\t\t\t\t-userCreated false\n\t\t\t\t-defaultImage \"vacantCell.xP:/\"\n\t\t\t\t-image \"\"\n\t\t\t\t-sc false\n\t\t\t\t-configString \"global string $gMainPane; paneLayout -e -cn \\\"single\\\" -ps 1 100 100 $gMainPane;\"\n\t\t\t\t-removeAllPanels\n\t\t\t\t-ap false\n\t\t\t\t\t(localizedPanelLabel(\"Persp View\")) \n\t\t\t\t\t\"modelPanel\"\n"
		+ "\t\t\t\t\t\"$panelName = `modelPanel -unParent -l (localizedPanelLabel(\\\"Persp View\\\")) -mbv $menusOkayInPanels `;\\n$editorName = $panelName;\\nmodelEditor -e \\n    -cam `findStartUpCamera persp` \\n    -useInteractiveMode 0\\n    -displayLights \\\"default\\\" \\n    -displayAppearance \\\"smoothShaded\\\" \\n    -activeOnly 0\\n    -ignorePanZoom 0\\n    -wireframeOnShaded 0\\n    -headsUpDisplay 1\\n    -holdOuts 1\\n    -selectionHiliteDisplay 1\\n    -useDefaultMaterial 0\\n    -bufferMode \\\"double\\\" \\n    -twoSidedLighting 0\\n    -backfaceCulling 0\\n    -xray 0\\n    -jointXray 0\\n    -activeComponentsXray 0\\n    -displayTextures 0\\n    -smoothWireframe 0\\n    -lineWidth 1\\n    -textureAnisotropic 0\\n    -textureHilight 1\\n    -textureSampling 2\\n    -textureDisplay \\\"modulate\\\" \\n    -textureMaxSize 32768\\n    -fogging 0\\n    -fogSource \\\"fragment\\\" \\n    -fogMode \\\"linear\\\" \\n    -fogStart 0\\n    -fogEnd 100\\n    -fogDensity 0.1\\n    -fogColor 0.5 0.5 0.5 1 \\n    -depthOfFieldPreview 1\\n    -maxConstantTransparency 1\\n    -rendererName \\\"vp2Renderer\\\" \\n    -objectFilterShowInHUD 1\\n    -isFiltered 0\\n    -colorResolution 256 256 \\n    -bumpResolution 512 512 \\n    -textureCompression 0\\n    -transparencyAlgorithm \\\"frontAndBackCull\\\" \\n    -transpInShadows 0\\n    -cullingOverride \\\"none\\\" \\n    -lowQualityLighting 0\\n    -maximumNumHardwareLights 1\\n    -occlusionCulling 0\\n    -shadingModel 0\\n    -useBaseRenderer 0\\n    -useReducedRenderer 0\\n    -smallObjectCulling 0\\n    -smallObjectThreshold -1 \\n    -interactiveDisableShadows 0\\n    -interactiveBackFaceCull 0\\n    -sortTransparent 1\\n    -controllers 1\\n    -nurbsCurves 1\\n    -nurbsSurfaces 1\\n    -polymeshes 1\\n    -subdivSurfaces 1\\n    -planes 1\\n    -lights 1\\n    -cameras 1\\n    -controlVertices 1\\n    -hulls 1\\n    -grid 1\\n    -imagePlane 1\\n    -joints 1\\n    -ikHandles 1\\n    -deformers 1\\n    -dynamics 1\\n    -particleInstancers 1\\n    -fluids 1\\n    -hairSystems 1\\n    -follicles 1\\n    -nCloths 1\\n    -nParticles 1\\n    -nRigids 1\\n    -dynamicConstraints 1\\n    -locators 1\\n    -manipulators 1\\n    -pluginShapes 1\\n    -dimensions 1\\n    -handles 1\\n    -pivots 1\\n    -textures 1\\n    -strokes 1\\n    -motionTrails 1\\n    -clipGhosts 1\\n    -greasePencils 0\\n    -shadows 0\\n    -captureSequenceNumber -1\\n    -width 643\\n    -height 648\\n    -sceneRenderFilter 0\\n    $editorName;\\nmodelEditor -e -viewSelected 0 $editorName;\\nmodelEditor -e \\n    -pluginObjects \\\"gpuCacheDisplayFilter\\\" 1 \\n    $editorName\"\n"
		+ "\t\t\t\t\t\"modelPanel -edit -l (localizedPanelLabel(\\\"Persp View\\\")) -mbv $menusOkayInPanels  $panelName;\\n$editorName = $panelName;\\nmodelEditor -e \\n    -cam `findStartUpCamera persp` \\n    -useInteractiveMode 0\\n    -displayLights \\\"default\\\" \\n    -displayAppearance \\\"smoothShaded\\\" \\n    -activeOnly 0\\n    -ignorePanZoom 0\\n    -wireframeOnShaded 0\\n    -headsUpDisplay 1\\n    -holdOuts 1\\n    -selectionHiliteDisplay 1\\n    -useDefaultMaterial 0\\n    -bufferMode \\\"double\\\" \\n    -twoSidedLighting 0\\n    -backfaceCulling 0\\n    -xray 0\\n    -jointXray 0\\n    -activeComponentsXray 0\\n    -displayTextures 0\\n    -smoothWireframe 0\\n    -lineWidth 1\\n    -textureAnisotropic 0\\n    -textureHilight 1\\n    -textureSampling 2\\n    -textureDisplay \\\"modulate\\\" \\n    -textureMaxSize 32768\\n    -fogging 0\\n    -fogSource \\\"fragment\\\" \\n    -fogMode \\\"linear\\\" \\n    -fogStart 0\\n    -fogEnd 100\\n    -fogDensity 0.1\\n    -fogColor 0.5 0.5 0.5 1 \\n    -depthOfFieldPreview 1\\n    -maxConstantTransparency 1\\n    -rendererName \\\"vp2Renderer\\\" \\n    -objectFilterShowInHUD 1\\n    -isFiltered 0\\n    -colorResolution 256 256 \\n    -bumpResolution 512 512 \\n    -textureCompression 0\\n    -transparencyAlgorithm \\\"frontAndBackCull\\\" \\n    -transpInShadows 0\\n    -cullingOverride \\\"none\\\" \\n    -lowQualityLighting 0\\n    -maximumNumHardwareLights 1\\n    -occlusionCulling 0\\n    -shadingModel 0\\n    -useBaseRenderer 0\\n    -useReducedRenderer 0\\n    -smallObjectCulling 0\\n    -smallObjectThreshold -1 \\n    -interactiveDisableShadows 0\\n    -interactiveBackFaceCull 0\\n    -sortTransparent 1\\n    -controllers 1\\n    -nurbsCurves 1\\n    -nurbsSurfaces 1\\n    -polymeshes 1\\n    -subdivSurfaces 1\\n    -planes 1\\n    -lights 1\\n    -cameras 1\\n    -controlVertices 1\\n    -hulls 1\\n    -grid 1\\n    -imagePlane 1\\n    -joints 1\\n    -ikHandles 1\\n    -deformers 1\\n    -dynamics 1\\n    -particleInstancers 1\\n    -fluids 1\\n    -hairSystems 1\\n    -follicles 1\\n    -nCloths 1\\n    -nParticles 1\\n    -nRigids 1\\n    -dynamicConstraints 1\\n    -locators 1\\n    -manipulators 1\\n    -pluginShapes 1\\n    -dimensions 1\\n    -handles 1\\n    -pivots 1\\n    -textures 1\\n    -strokes 1\\n    -motionTrails 1\\n    -clipGhosts 1\\n    -greasePencils 0\\n    -shadows 0\\n    -captureSequenceNumber -1\\n    -width 643\\n    -height 648\\n    -sceneRenderFilter 0\\n    $editorName;\\nmodelEditor -e -viewSelected 0 $editorName;\\nmodelEditor -e \\n    -pluginObjects \\\"gpuCacheDisplayFilter\\\" 1 \\n    $editorName\"\n"
		+ "\t\t\t\t$configName;\n\n            setNamedPanelLayout (localizedPanelLabel(\"Current Layout\"));\n        }\n\n        panelHistory -e -clear mainPanelHistory;\n        sceneUIReplacement -clear;\n\t}\n\n\ngrid -spacing 5 -size 12 -divisions 5 -displayAxes yes -displayGridLines yes -displayDivisionLines yes -displayPerspectiveLabels no -displayOrthographicLabels no -displayAxesBold yes -perspectiveLabelPosition axis -orthographicLabelPosition edge;\nviewManip -drawCompass 0 -compassAngle 0 -frontParameters \"\" -homeParameters \"\" -selectionLockParameters \"\";\n}\n");
	setAttr ".st" 3;
createNode script -n "sceneConfigurationScriptNode";
	rename -uid "2D447938-4933-401C-64D2-AEAC330DC8EC";
	setAttr ".b" -type "string" "playbackOptions -min 537 -max 583 -ast 0 -aet 3000 ";
	setAttr ".st" 6;
createNode renderSetup -n "renderSetup";
	rename -uid "487C8798-4711-F657-7E5D-0EA5789E88EA";
createNode renderSetupLayer -n "layerFrameRange1";
	rename -uid "7AE68437-46F9-A1DD-5A41-63B51BBD80B0";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".es" yes;
createNode renderLayer -n "rs_layerFrameRange1";
	rename -uid "8DF116B9-4F5C-E75A-8CE7-C59389A78B5B";
	setAttr ".do" 1;
createNode renderSetupLayer -n "renderSetupLayer2";
	rename -uid "F93DD273-478D-AE2B-6B5F-76AAEFB7E86D";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".es" yes;
createNode renderLayer -n "rs_renderSetupLayer2";
	rename -uid "783B4028-4516-C4EE-2D07-66BBF19BD598";
	setAttr ".do" 2;
createNode renderSetupLayer -n "layerDefaultFrames";
	rename -uid "D4754C0E-4A0C-4A0D-D568-5FBC261281BC";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".es" yes;
createNode renderLayer -n "rs_layerDefaultFrames";
	rename -uid "3A84A611-4577-CC3B-511B-258E6BB67164";
	setAttr ".adjs[0].val" 0;
	setAttr ".do" 3;
createNode renderSetupLayer -n "renderSetupLayer4";
	rename -uid "062BB0BE-4CBF-0C59-EBBE-268602E033B0";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".es" yes;
createNode renderLayer -n "rs_renderSetupLayer4";
	rename -uid "4598583D-42BA-CC1C-90B6-A2BE12D2C1B3";
	setAttr ".do" 4;
createNode renderSettingsCollection -n "RenderSettingsCollection";
	rename -uid "AC2872AB-4A14-2350-4B02-B68D409E35CD";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".es" yes;
createNode simpleSelector -n "RenderSettingsCollectionSelector";
	rename -uid "2917EC4C-4981-BC5B-5102-30807E447169";
	setAttr ".ssl" -type "string" "defaultRenderGlobals\ndefaultRenderQuality\ndefaultArnoldDriver\ndefaultArnoldRenderOptions\ndefaultArnoldFilter\ndefaultResolution";
	setAttr ".tf" 0;
createNode absUniqueOverride -n "startFrame";
	rename -uid "04685661-4BEF-93AF-D454-4294D809CE8E";
	addAttr -ci true -sn "atv" -ln "attrValue" -at "time";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".atr" -type "string" "startFrame";
	setAttr ".tgName" -type "string" "defaultRenderGlobals";
	setAttr ".atv" 1;
	setAttr ".es" yes;
createNode absUniqueOverride -n "endFrame";
	rename -uid "9AF891A9-4DEF-78B9-EC55-71957A6C82EC";
	addAttr -ci true -sn "atv" -ln "attrValue" -at "time";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".atr" -type "string" "endFrame";
	setAttr ".tgName" -type "string" "defaultRenderGlobals";
	setAttr ".atv" 10;
	setAttr ".es" yes;
createNode renderSettingsCollection -n "RenderSettingsCollection1";
	rename -uid "86CC09CF-46EE-0771-3808-7EB13F120D0B";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".es" yes;
createNode simpleSelector -n "RenderSettingsCollection1Selector";
	rename -uid "C093FCE1-4873-30DE-037C-8D95CCC53B84";
	setAttr ".ssl" -type "string" "defaultRenderGlobals\ndefaultRenderQuality\ndefaultArnoldDriver\ndefaultArnoldRenderOptions\ndefaultArnoldFilter\ndefaultResolution";
	setAttr ".tf" 0;
createNode absUniqueOverride -n "startFrame1";
	rename -uid "817DBE19-486A-B79E-3983-BBA7EC2153A3";
	addAttr -ci true -sn "atv" -ln "attrValue" -at "time";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".atr" -type "string" "startFrame";
	setAttr ".tgName" -type "string" "defaultRenderGlobals";
	setAttr ".atv" 20;
	setAttr ".es" yes;
createNode absUniqueOverride -n "endFrame1";
	rename -uid "261CBD69-468B-6A2C-8D7D-A8924C94199D";
	addAttr -ci true -sn "atv" -ln "attrValue" -at "time";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".atr" -type "string" "endFrame";
	setAttr ".tgName" -type "string" "defaultRenderGlobals";
	setAttr ".atv" 30;
	setAttr ".es" yes;
createNode renderSettingsCollection -n "RenderSettingsCollection2";
	rename -uid "65830317-45E4-1475-4366-F29C6194EBB3";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".es" yes;
createNode simpleSelector -n "RenderSettingsCollection2Selector";
	rename -uid "721DE8B5-41FA-2D81-B52E-CE856DFC6665";
	setAttr ".ssl" -type "string" "defaultRenderGlobals\ndefaultRenderQuality\ndefaultArnoldDriver\ndefaultArnoldRenderOptions\ndefaultArnoldFilter\ndefaultResolution";
	setAttr ".tf" 0;
createNode relUniqueOverride -n "endFrame2";
	rename -uid "C0086DFB-452A-6B3E-E9C6-06B0013AABA9";
	addAttr -ci true -sn "mul" -ln "multiply" -smn 0 -smx 2 -at "float";
	addAttr -ci true -sn "ofs" -ln "offset" -at "time";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".atr" -type "string" "endFrame";
	setAttr ".tgName" -type "string" "defaultRenderGlobals";
	setAttr ".mul" 1;
	setAttr ".ofs" 10;
	setAttr ".es" yes;
createNode lightEditor -n "lightEditor";
	rename -uid "484084A9-45F9-291C-C28C-D18A056FE958";
createNode lightItem -n "pointLightShape1__LEItem";
	rename -uid "479A7CA1-4A93-D7CC-B549-0BA93D1CBE6E";
createNode renderSettingsChildCollection -n "renderSettingsChildCollection1";
	rename -uid "EE957B2D-44C7-02B0-1EC0-48BDFCAE59F5";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".es" yes;
createNode simpleSelector -n "renderSettingsChildCollection1Selector";
	rename -uid "60F1673D-4D79-0218-F6F9-7593E643089C";
	setAttr ".ssl" -type "string" "hardwareRenderingGlobals\ndefaultRenderGlobals\ndefaultRenderQuality\ndefaultResolution";
	setAttr ".tf" 0;
createNode lightsCollection -n "lightsCollection";
	rename -uid "71DC1C19-407F-1918-1C24-44B5BBAC58FD";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".es" yes;
createNode lightsCollectionSelector -n "lightsCollectionSelector";
	rename -uid "B6BCFF66-4643-FC8A-FF56-D2BEFF9E770B";
	setAttr ".pat" -type "string" "*";
	setAttr ".ssl" -type "string" "|pointLight1|pointLightShape1";
	setAttr ".tf" 4;
createNode lightsChildCollection -n "_pointLight1_pointLightShape1_col";
	rename -uid "B7535024-4988-5C18-7AE0-5A9E34C987DB";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".es" yes;
createNode lightsCollectionSelector -n "_pointLight1_pointLightShape1_colSelector";
	rename -uid "9D4BE329-4665-D5F7-71B7-F0845B10C695";
	setAttr ".ssl" -type "string" "|pointLight1|pointLightShape1";
	setAttr ".tf" 12;
createNode absOverride -n "intensity";
	rename -uid "44875C81-4C65-C460-0745-7A99BADF3E2A";
	addAttr -ci true -k true -sn "atv" -ln "attrValue" -smn 0 -smx 10 -at "float";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".atr" -type "string" "intensity";
	setAttr -k on ".atv" 3.4389140605926514;
	setAttr ".es" yes;
createNode collection -n "collection1";
	rename -uid "453E57D5-4E0A-915F-F656-43B2F4F27BBF";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".es" yes;
createNode simpleSelector -n "collection1Selector";
	rename -uid "219EA44D-491C-5A3D-243C-968FFD6847B8";
	setAttr ".ssl" -type "string" "|pointLight1|pointLightShape1";
	setAttr ".tf" 4;
createNode reference -n "scene_file_to_referenceRN";
	rename -uid "C918C559-4A3A-DEDF-08EC-F796E312D2DE";
	setAttr ".ed" -type "dataReferenceEdits" 
		"scene_file_to_referenceRN"
		"scene_file_to_referenceRN" 0;
	setAttr ".ptag" -type "string" "";
lockNode -l 1 ;
createNode renderSetupLayer -n "notRenderableLayer";
	rename -uid "FC55F17C-4984-F893-8BA0-44B75C232D4C";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".es" yes;
createNode renderLayer -n "rs_notRenderableLayer";
	rename -uid "6133420E-4D77-7C31-0B0C-7DB503A88EEA";
	setAttr ".rndr" no;
	setAttr ".do" 5;
createNode collection -n "collection2";
	rename -uid "DC4D307D-4108-41F0-45CB-C29C7EAC14F2";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".es" yes;
createNode simpleSelector -n "collection2Selector";
	rename -uid "C639EE71-4186-2569-1F92-3C962C84D34A";
createNode group -n "group1";
	rename -uid "40E82D6F-4067-1264-73AB-C2A4194373B6";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".es" yes;
createNode renderSettingsCollection -n "RenderSettingsCollection3";
	rename -uid "5E12D6E8-457D-9ECD-CD36-8CA25CF621F5";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".es" yes;
createNode simpleSelector -n "RenderSettingsCollection3Selector";
	rename -uid "D4CFB0A1-4BA3-D4AF-435D-9781B27D81A1";
	setAttr ".ssl" -type "string" "hardwareRenderingGlobals\ndefaultRenderGlobals\ndefaultRenderQuality\ndefaultResolution";
	setAttr ".tf" 0;
createNode relUniqueOverride -n "startFrame2";
	rename -uid "13E696E5-43DB-A550-A4ED-03B6B7251AF2";
	addAttr -ci true -sn "mul" -ln "multiply" -smn 0 -smx 2 -at "float";
	addAttr -ci true -sn "ofs" -ln "offset" -at "time";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".atr" -type "string" "startFrame";
	setAttr ".tgName" -type "string" "defaultRenderGlobals";
	setAttr ".mul" 1;
	setAttr ".ofs" 4;
	setAttr ".es" yes;
createNode collection -n "_persp_perspShape_col";
	rename -uid "E7E9EE35-4E95-7072-C5DB-F19C423C4296";
createNode simpleSelector -n "_persp_perspShape_colSelector";
	rename -uid "8D43BE0A-435E-EEF0-0141-63B11171F487";
	setAttr ".ssl" -type "string" "|persp|perspShape";
	setAttr ".tf" 2;
createNode absOverride -n "renderable";
	rename -uid "7A6AEA1B-4C7B-7E79-EEB0-E6993521CB88";
	addAttr -ci true -sn "atv" -ln "attrValue" -min 0 -max 1 -at "bool";
	setAttr ".atr" -type "string" "renderable";
createNode collection -n "_persp_perspShape_col1";
	rename -uid "9943D2B9-49BD-1680-D9EB-92BE01FDDC29";
createNode simpleSelector -n "_persp_perspShape_col1Selector";
	rename -uid "49C5E271-4F77-35B6-D65A-319F3D9A121D";
	setAttr ".ssl" -type "string" "|persp|perspShape";
	setAttr ".tf" 2;
createNode absOverride -n "mask";
	rename -uid "72A299A0-4C7E-2B8D-1645-57B49C5EA1F4";
	addAttr -ci true -sn "atv" -ln "attrValue" -min 0 -max 1 -at "bool";
	setAttr ".atr" -type "string" "mask";
	setAttr ".atv" yes;
createNode absOverride -n "renderable1";
	rename -uid "8976706B-4C45-C505-F399-F193EBB9C151";
	addAttr -ci true -sn "atv" -ln "attrValue" -min 0 -max 1 -at "bool";
	setAttr ".atr" -type "string" "renderable";
createNode collection -n "_camera3_cameraShape3_col";
	rename -uid "7186B93E-4C89-24BE-BC3D-E586E56DF5B6";
createNode simpleSelector -n "_camera3_cameraShape3_colSelector";
	rename -uid "80D54FF1-4621-8A36-89F2-949F8735724A";
	setAttr ".ssl" -type "string" "|camera3|cameraShape3";
	setAttr ".tf" 2;
createNode absOverride -n "renderable2";
	rename -uid "785A0D3F-454A-6C00-327B-B5B9D2F55C77";
	addAttr -ci true -sn "atv" -ln "attrValue" -min 0 -max 1 -at "bool";
	setAttr ".atr" -type "string" "renderable";
	setAttr ".atv" yes;
createNode collection -n "_camera2_cameraShape2_col";
	rename -uid "DBEA4EB9-4BE4-90B3-6B64-DAA94C76EEFA";
createNode simpleSelector -n "_camera2_cameraShape2_colSelector";
	rename -uid "8CBEB361-4438-B81F-C3A6-0F9BDFDBCBCC";
	setAttr ".ssl" -type "string" "|camera2|cameraShape2";
	setAttr ".tf" 2;
createNode absOverride -n "renderable3";
	rename -uid "B0F561AC-49CE-63F1-529F-D981C7C52177";
	addAttr -ci true -sn "atv" -ln "attrValue" -min 0 -max 1 -at "bool";
	setAttr ".atr" -type "string" "renderable";
	setAttr ".atv" yes;
createNode collection -n "_camera1_cameraShape1_col";
	rename -uid "52864840-4BCB-98DD-21FB-828650A559C8";
createNode simpleSelector -n "_camera1_cameraShape1_colSelector";
	rename -uid "3A6DD9F2-44BF-3845-090B-B79E5C074008";
	setAttr ".ssl" -type "string" "|camera1|cameraShape1";
	setAttr ".tf" 2;
createNode absOverride -n "renderable4";
	rename -uid "CB8C71C4-45A5-64B8-949B-E88D7557BEC4";
	addAttr -ci true -sn "atv" -ln "attrValue" -min 0 -max 1 -at "bool";
	setAttr ".atr" -type "string" "renderable";
	setAttr ".atv" yes;
createNode collection -n "_camera1_cameraShape1_col1";
	rename -uid "91217061-4541-AD62-0101-B7A688679587";
createNode simpleSelector -n "_camera1_cameraShape1_col1Selector";
	rename -uid "70D8112D-41F7-22C4-1682-F9A886245728";
	setAttr ".ssl" -type "string" "|camera1|cameraShape1";
	setAttr ".tf" 2;
createNode absOverride -n "renderable5";
	rename -uid "84C758C6-4B47-7561-F80B-A1ABABCC5806";
	addAttr -ci true -sn "atv" -ln "attrValue" -min 0 -max 1 -at "bool";
	setAttr ".atr" -type "string" "renderable";
	setAttr ".atv" yes;
createNode applyRelFloatOverride -n "startFrame2_defaultRenderGlobals_fs";
	rename -uid "060028D2-47AC-3161-DAF4-19B4B3ED5557";
	setAttr ".ori" 1;
createNode unitToTimeConversion -n "unitToTimeConversion1";
	rename -uid "05481504-41CD-E5D2-74FA-59ABB4D0263D";
	setAttr ".cf" 250;
createNode timeToUnitConversion -n "timeToUnitConversion1";
	rename -uid "836C4EA3-4FFF-FCBC-0C0B-F99DDDB434A4";
	setAttr ".cf" 0.004;
select -ne :time1;
	setAttr ".o" 537;
	setAttr ".unw" 537;
select -ne :hardwareRenderingGlobals;
	setAttr ".otfna" -type "stringArray" 22 "NURBS Curves" "NURBS Surfaces" "Polygons" "Subdiv Surface" "Particles" "Particle Instance" "Fluids" "Strokes" "Image Planes" "UI" "Lights" "Cameras" "Locators" "Joints" "IK Handles" "Deformers" "Motion Trails" "Components" "Hair Systems" "Follicles" "Misc. UI" "Ornaments"  ;
	setAttr ".otfva" -type "Int32Array" 22 0 1 1 1 1 1
		 1 1 1 0 0 0 0 0 0 0 0 0
		 0 0 0 0 ;
	setAttr ".fprt" yes;
select -ne :renderPartition;
	setAttr -s 2 ".st";
select -ne :renderGlobalsList1;
select -ne :defaultShaderList1;
	setAttr -s 5 ".s";
select -ne :postProcessList1;
	setAttr -s 2 ".p";
select -ne :defaultRenderingList1;
	setAttr -s 7 ".r";
select -ne :lightList1;
select -ne :initialShadingGroup;
	setAttr ".ro" yes;
select -ne :initialParticleSE;
	setAttr ".ro" yes;
select -ne :defaultRenderGlobals;
	addAttr -ci true -h true -sn "dss" -ln "defaultSurfaceShader" -dt "string";
	setAttr ".ren" -type "string" "mayaHardware2";
	setAttr ".imfkey" -type "string" "exr";
	setAttr ".an" yes;
	setAttr ".pff" yes;
	setAttr ".dss" -type "string" "lambert1";
select -ne :defaultResolution;
	setAttr ".pa" 1;
select -ne :defaultLightSet;
select -ne :defaultColorMgtGlobals;
	setAttr ".cfe" yes;
	setAttr ".cfp" -type "string" "<MAYA_RESOURCES>/OCIO-configs/Maya2022-default/config.ocio";
	setAttr ".vtn" -type "string" "ACES 1.0 SDR-video (sRGB)";
	setAttr ".vn" -type "string" "ACES 1.0 SDR-video";
	setAttr ".dn" -type "string" "sRGB";
	setAttr ".wsn" -type "string" "ACEScg";
	setAttr ".otn" -type "string" "ACES 1.0 SDR-video (sRGB)";
	setAttr ".potn" -type "string" "ACES 1.0 SDR-video (sRGB)";
select -ne :hardwareRenderGlobals;
	setAttr ".ctrs" 256;
	setAttr ".btrs" 512;
connectAttr "rs_renderSetupLayer2.ri" ":perspShape.rlio[0]";
connectAttr "rs_layerDefaultFrames.ri" ":perspShape.rlio[1]";
connectAttr "rs_renderSetupLayer2.ri" "cameraShape1.rlio[0]";
connectAttr "rs_layerFrameRange1.ri" "cameraShape1.rlio[1]";
connectAttr "rs_renderSetupLayer2.ri" "cameraShape2.rlio[0]";
connectAttr "rs_renderSetupLayer2.ri" "cameraShape3.rlio[0]";
connectAttr "polySphere1.out" "pSphereShape1.i";
connectAttr "rs_renderSetupLayer2.ri" "pointLight1.rlio[0]";
connectAttr "pointLightShape1__LEItem.en" "pointLightShape1.v";
connectAttr "rs_notRenderableLayer.ri" "pointLightShape1.rlio[0]";
connectAttr "rs_layerFrameRange1.ri" "pointLightShape1.rlio[1]";
connectAttr "rs_layerDefaultFrames.ri" "pointLightShape1.rlio[2]";
connectAttr "rs_renderSetupLayer4.ri" "pointLightShape1.rlio[3]";
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
connectAttr "layerManager.dli[0]" "defaultLayer.id";
connectAttr "renderLayerManager.rlmi[0]" "defaultRenderLayer.rlid";
connectAttr "cameraShape1.rnd" "defaultRenderLayer.adjs[0].plg";
connectAttr ":defaultArnoldDisplayDriver.msg" ":defaultArnoldRenderOptions.drivers"
		 -na;
connectAttr ":defaultArnoldFilter.msg" ":defaultArnoldRenderOptions.filt";
connectAttr ":defaultArnoldDriver.msg" ":defaultArnoldRenderOptions.drvr";
connectAttr "layerFrameRange1.msg" "renderSetup.frl";
connectAttr "notRenderableLayer.msg" "renderSetup.lrl";
connectAttr "rs_layerFrameRange1.msg" "layerFrameRange1.lrl";
connectAttr "renderSetup.lit" "layerFrameRange1.pls";
connectAttr "_camera1_cameraShape1_col1.msg" "layerFrameRange1.ch";
connectAttr "RenderSettingsCollection.msg" "layerFrameRange1.cl";
connectAttr "renderLayerManager.rlmi[1]" "rs_layerFrameRange1.rlid";
connectAttr "rs_renderSetupLayer2.msg" "renderSetupLayer2.lrl";
connectAttr "layerFrameRange1.nxt" "renderSetupLayer2.prv";
connectAttr "renderSetup.lit" "renderSetupLayer2.pls";
connectAttr "_camera1_cameraShape1_col.msg" "renderSetupLayer2.ch";
connectAttr "RenderSettingsCollection1.msg" "renderSetupLayer2.cl";
connectAttr "renderLayerManager.rlmi[2]" "rs_renderSetupLayer2.rlid";
connectAttr "rs_layerDefaultFrames.msg" "layerDefaultFrames.lrl";
connectAttr "renderSetupLayer2.nxt" "layerDefaultFrames.prv";
connectAttr "renderSetup.lit" "layerDefaultFrames.pls";
connectAttr "_persp_perspShape_col1.msg" "layerDefaultFrames.cl";
connectAttr "_persp_perspShape_col1.msg" "layerDefaultFrames.ch";
connectAttr "renderLayerManager.rlmi[3]" "rs_layerDefaultFrames.rlid";
connectAttr "cameraShape1.rnd" "rs_layerDefaultFrames.adjs[0].plg";
connectAttr "rs_renderSetupLayer4.msg" "renderSetupLayer4.lrl";
connectAttr "layerDefaultFrames.nxt" "renderSetupLayer4.prv";
connectAttr "renderSetup.lit" "renderSetupLayer4.pls";
connectAttr "RenderSettingsCollection2.msg" "renderSetupLayer4.ch";
connectAttr "RenderSettingsCollection2.msg" "renderSetupLayer4.cl";
connectAttr "renderLayerManager.rlmi[4]" "rs_renderSetupLayer4.rlid";
connectAttr "RenderSettingsCollectionSelector.c" "RenderSettingsCollection.sel";
connectAttr "layerFrameRange1.lit" "RenderSettingsCollection.pls";
connectAttr "layerFrameRange1.nic" "RenderSettingsCollection.pic";
connectAttr "startFrame.msg" "RenderSettingsCollection.cl";
connectAttr "renderSettingsChildCollection1.msg" "RenderSettingsCollection.ch";
connectAttr "RenderSettingsCollection.lit" "startFrame.pls";
connectAttr "RenderSettingsCollection.en" "startFrame.pen";
connectAttr "startFrame.nxt" "endFrame.prv";
connectAttr "RenderSettingsCollection.lit" "endFrame.pls";
connectAttr "RenderSettingsCollection.en" "endFrame.pen";
connectAttr "RenderSettingsCollection1Selector.c" "RenderSettingsCollection1.sel"
		;
connectAttr "renderSetupLayer2.lit" "RenderSettingsCollection1.pls";
connectAttr "renderSetupLayer2.nic" "RenderSettingsCollection1.pic";
connectAttr "startFrame1.msg" "RenderSettingsCollection1.cl";
connectAttr "endFrame1.msg" "RenderSettingsCollection1.ch";
connectAttr "RenderSettingsCollection1.lit" "startFrame1.pls";
connectAttr "RenderSettingsCollection1.en" "startFrame1.pen";
connectAttr "startFrame1.nxt" "endFrame1.prv";
connectAttr "RenderSettingsCollection1.lit" "endFrame1.pls";
connectAttr "RenderSettingsCollection1.en" "endFrame1.pen";
connectAttr "RenderSettingsCollection2Selector.c" "RenderSettingsCollection2.sel"
		;
connectAttr "renderSetupLayer4.lit" "RenderSettingsCollection2.pls";
connectAttr "renderSetupLayer4.nic" "RenderSettingsCollection2.pic";
connectAttr "endFrame2.msg" "RenderSettingsCollection2.cl";
connectAttr "endFrame2.msg" "RenderSettingsCollection2.ch";
connectAttr "RenderSettingsCollection2.lit" "endFrame2.pls";
connectAttr "RenderSettingsCollection2.en" "endFrame2.pen";
connectAttr "pointLightShape1__LEItem.msg" "lightEditor.fi";
connectAttr "pointLightShape1__LEItem.msg" "lightEditor.li";
connectAttr "pointLightShape1.msg" "pointLightShape1__LEItem.lgt";
connectAttr "lightEditor.lit" "pointLightShape1__LEItem.pls";
connectAttr "lightEditor.en" "pointLightShape1__LEItem.pen";
connectAttr "lightEditor.nic" "pointLightShape1__LEItem.pic";
connectAttr "renderSettingsChildCollection1Selector.c" "renderSettingsChildCollection1.sel"
		;
connectAttr "endFrame.nxt" "renderSettingsChildCollection1.prv";
connectAttr "RenderSettingsCollection.lit" "renderSettingsChildCollection1.pls";
connectAttr "RenderSettingsCollection.en" "renderSettingsChildCollection1.pen";
connectAttr "RenderSettingsCollection.nrc" "renderSettingsChildCollection1.pic";
connectAttr "RenderSettingsCollectionSelector.out" "renderSettingsChildCollection1Selector.in"
		;
connectAttr "lightsCollectionSelector.c" "lightsCollection.sel";
connectAttr "RenderSettingsCollection1.nxt" "lightsCollection.prv";
connectAttr "renderSetupLayer2.lit" "lightsCollection.pls";
connectAttr "renderSetupLayer2.nic" "lightsCollection.pic";
connectAttr "_pointLight1_pointLightShape1_col.msg" "lightsCollection.cl";
connectAttr "_pointLight1_pointLightShape1_col.msg" "lightsCollection.ch";
connectAttr "_pointLight1_pointLightShape1_colSelector.c" "_pointLight1_pointLightShape1_col.sel"
		;
connectAttr "lightsCollection.lit" "_pointLight1_pointLightShape1_col.pls";
connectAttr "lightsCollection.en" "_pointLight1_pointLightShape1_col.pen";
connectAttr "renderSetupLayer2.nic" "_pointLight1_pointLightShape1_col.pic";
connectAttr "intensity.msg" "_pointLight1_pointLightShape1_col.cl";
connectAttr "intensity.msg" "_pointLight1_pointLightShape1_col.ch";
connectAttr "lightsCollectionSelector.out" "_pointLight1_pointLightShape1_colSelector.in"
		;
connectAttr "_pointLight1_pointLightShape1_col.lit" "intensity.pls";
connectAttr "_pointLight1_pointLightShape1_col.en" "intensity.pen";
connectAttr "collection1Selector.c" "collection1.sel";
connectAttr "RenderSettingsCollection.nxt" "collection1.prv";
connectAttr "layerFrameRange1.lit" "collection1.pls";
connectAttr "layerFrameRange1.nic" "collection1.pic";
connectAttr "rs_notRenderableLayer.msg" "notRenderableLayer.lrl";
connectAttr "renderSetupLayer4.nxt" "notRenderableLayer.prv";
connectAttr "renderSetup.lit" "notRenderableLayer.pls";
connectAttr "RenderSettingsCollection3.msg" "notRenderableLayer.cl";
connectAttr "group1.msg" "notRenderableLayer.ch";
connectAttr "renderLayerManager.rlmi[5]" "rs_notRenderableLayer.rlid";
connectAttr "collection2Selector.c" "collection2.sel";
connectAttr "notRenderableLayer.lit" "collection2.pls";
connectAttr "notRenderableLayer.nic" "collection2.pic";
connectAttr "RenderSettingsCollection3.nxt" "collection2.prv";
connectAttr "collection2.nxt" "group1.prv";
connectAttr "notRenderableLayer.lit" "group1.pls";
connectAttr "notRenderableLayer.nic" "group1.pic";
connectAttr "RenderSettingsCollection3Selector.c" "RenderSettingsCollection3.sel"
		;
connectAttr "notRenderableLayer.lit" "RenderSettingsCollection3.pls";
connectAttr "notRenderableLayer.nic" "RenderSettingsCollection3.pic";
connectAttr "startFrame2.msg" "RenderSettingsCollection3.cl";
connectAttr "startFrame2.msg" "RenderSettingsCollection3.ch";
connectAttr "RenderSettingsCollection3.lit" "startFrame2.pls";
connectAttr "RenderSettingsCollection3.en" "startFrame2.pen";
connectAttr "_persp_perspShape_colSelector.c" "_persp_perspShape_col.sel";
connectAttr "lightsCollection.nxt" "_persp_perspShape_col.prv";
connectAttr "renderSetupLayer2.lit" "_persp_perspShape_col.pls";
connectAttr "renderSetupLayer2.nic" "_persp_perspShape_col.pic";
connectAttr "renderable.msg" "_persp_perspShape_col.cl";
connectAttr "renderable.msg" "_persp_perspShape_col.ch";
connectAttr "_persp_perspShape_col.lit" "renderable.pls";
connectAttr "_persp_perspShape_col.en" "renderable.pen";
connectAttr "_persp_perspShape_col1Selector.c" "_persp_perspShape_col1.sel";
connectAttr "layerDefaultFrames.lit" "_persp_perspShape_col1.pls";
connectAttr "layerDefaultFrames.nic" "_persp_perspShape_col1.pic";
connectAttr "mask.msg" "_persp_perspShape_col1.cl";
connectAttr "renderable1.msg" "_persp_perspShape_col1.ch";
connectAttr "_persp_perspShape_col1.lit" "mask.pls";
connectAttr "_persp_perspShape_col1.en" "mask.pen";
connectAttr "mask.nxt" "renderable1.prv";
connectAttr "_persp_perspShape_col1.lit" "renderable1.pls";
connectAttr "_persp_perspShape_col1.en" "renderable1.pen";
connectAttr "_camera3_cameraShape3_colSelector.c" "_camera3_cameraShape3_col.sel"
		;
connectAttr "_persp_perspShape_col.nxt" "_camera3_cameraShape3_col.prv";
connectAttr "renderSetupLayer2.lit" "_camera3_cameraShape3_col.pls";
connectAttr "renderSetupLayer2.nic" "_camera3_cameraShape3_col.pic";
connectAttr "renderable2.msg" "_camera3_cameraShape3_col.cl";
connectAttr "renderable2.msg" "_camera3_cameraShape3_col.ch";
connectAttr "_camera3_cameraShape3_col.lit" "renderable2.pls";
connectAttr "_camera3_cameraShape3_col.en" "renderable2.pen";
connectAttr "_camera2_cameraShape2_colSelector.c" "_camera2_cameraShape2_col.sel"
		;
connectAttr "_camera3_cameraShape3_col.nxt" "_camera2_cameraShape2_col.prv";
connectAttr "renderSetupLayer2.lit" "_camera2_cameraShape2_col.pls";
connectAttr "renderSetupLayer2.nic" "_camera2_cameraShape2_col.pic";
connectAttr "renderable3.msg" "_camera2_cameraShape2_col.cl";
connectAttr "renderable3.msg" "_camera2_cameraShape2_col.ch";
connectAttr "_camera2_cameraShape2_col.lit" "renderable3.pls";
connectAttr "_camera2_cameraShape2_col.en" "renderable3.pen";
connectAttr "_camera1_cameraShape1_colSelector.c" "_camera1_cameraShape1_col.sel"
		;
connectAttr "_camera2_cameraShape2_col.nxt" "_camera1_cameraShape1_col.prv";
connectAttr "renderSetupLayer2.lit" "_camera1_cameraShape1_col.pls";
connectAttr "renderSetupLayer2.nic" "_camera1_cameraShape1_col.pic";
connectAttr "renderable4.msg" "_camera1_cameraShape1_col.cl";
connectAttr "renderable4.msg" "_camera1_cameraShape1_col.ch";
connectAttr "_camera1_cameraShape1_col.lit" "renderable4.pls";
connectAttr "_camera1_cameraShape1_col.en" "renderable4.pen";
connectAttr "_camera1_cameraShape1_col1Selector.c" "_camera1_cameraShape1_col1.sel"
		;
connectAttr "collection1.nxt" "_camera1_cameraShape1_col1.prv";
connectAttr "layerFrameRange1.lit" "_camera1_cameraShape1_col1.pls";
connectAttr "layerFrameRange1.nic" "_camera1_cameraShape1_col1.pic";
connectAttr "renderable5.msg" "_camera1_cameraShape1_col1.cl";
connectAttr "renderable5.msg" "_camera1_cameraShape1_col1.ch";
connectAttr "_camera1_cameraShape1_col1.lit" "renderable5.pls";
connectAttr "_camera1_cameraShape1_col1.en" "renderable5.pen";
connectAttr "startFrame2.en" "startFrame2_defaultRenderGlobals_fs.en";
connectAttr "startFrame2.mul" "startFrame2_defaultRenderGlobals_fs.mul";
connectAttr "timeToUnitConversion1.o" "startFrame2_defaultRenderGlobals_fs.ofs";
connectAttr "startFrame2_defaultRenderGlobals_fs.o" "unitToTimeConversion1.i";
connectAttr "startFrame2.ofs" "timeToUnitConversion1.i";
connectAttr "defaultRenderLayer.msg" ":defaultRenderingList1.r" -na;
connectAttr "rs_layerFrameRange1.msg" ":defaultRenderingList1.r" -na;
connectAttr "rs_renderSetupLayer2.msg" ":defaultRenderingList1.r" -na;
connectAttr "rs_layerDefaultFrames.msg" ":defaultRenderingList1.r" -na;
connectAttr "rs_renderSetupLayer4.msg" ":defaultRenderingList1.r" -na;
connectAttr "rs_notRenderableLayer.msg" ":defaultRenderingList1.r" -na;
connectAttr "pointLightShape1.ltd" ":lightList1.l" -na;
connectAttr "pSphereShape1.iog" ":initialShadingGroup.dsm" -na;
connectAttr "unitToTimeConversion1.o" ":defaultRenderGlobals.fs";
connectAttr "pointLight1.iog" ":defaultLightSet.dsm" -na;
// End of layers.ma
