
inputs:
  semver:
    required: true
    type: string
  tag:
    required: true
    type: string

runs:
  using: composite
  steps:
  - name: Zip submitter plugin
    shell: bash
    run: |
      mkdir dist_extras
      cd maya_submitter_plugin 
      zip -r  ../dist_extras/maya_submitter_plugin_${{inputs.semver}}.zip .
      cd ..
