
inputs:
  semver:
    required: true
    type: string

runs:
  using: composite
  steps:
  - name: Update plugin Version
    shell: bash
    env:
      SEMVER: ${{ inputs.semver }}
    run: |
      echo "+ DeadlineCloudForMaya ${SEMVER} ." > ./maya_submitter_plugin/DeadlineCloudForMaya.mod
      sed -i "s/^VERSION =.*/VERSION = \"${SEMVER}\"/" ./maya_submitter_plugin/plug-ins/DeadlineCloudForMaya.py
      git add ./maya_submitter_plugin/DeadlineCloudForMaya.mod ./maya_submitter_plugin/plug-ins/DeadlineCloudForMaya.py
