name: Maya Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'feat/integ-test-cicd-v2-fork-test'

jobs:
  IntegrationTests:
    name: ${{ matrix.name }} Integration Tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: mainline
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            name: Linux
            project_suffix: linux-integ
          - os: windows
            name: Windows
            project_suffix: windows-integ
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CODEBUILD_MAINLINE_INTEG_ROLE }}
          aws-region: us-west-2

      - name: Start CodeBuild
        id: codebuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: deadline-cloud-for-maya-mainline-${{ matrix.project_suffix }}
          source-location-override: ${{ github.server_url }}/${{ github.repository }}.git
          source-version-override: refs/heads/${{ github.ref_name }}
          hide-cloudwatch-logs: true
