name: Maya Integration Tests

on:
  workflow_dispatch:
    inputs:
      ref_type:
        description: 'Reference type to test'
        required: true
        default: 'branch'
        type: choice
        options:
          - branch
          - tag
      branch:
        description: 'Branch to test (e.g., mainline, feature-branch)'
        required: false
        default: 'mainline'
        type: string
      tag:
        description: 'Tag to test (only used when ref_type is "tag")'
        required: false
        type: string
  push:
    branches:
      - 'mainline'
      - 'feat/integ-test-cicd'

jobs:
  IntegrationTests:
    name: ${{ matrix.name }} Integration Tests
    runs-on: ubuntu-latest
    environment: mainline
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            name: Linux
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CODEBUILD_MAINLINE_INTEG_ROLE }}
          aws-region: us-west-2
          mask-aws-account-id: true

      - name: Run Integration Tests
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: deadline-cloud-for-maya-mainline-${{ matrix.os }}-integ
          hide-cloudwatch-logs: true
          source-version-override: ${{ github.event.inputs.ref_type == 'tag' && format('refs/tags/{0}', github.event.inputs.tag) || github.event.inputs.branch || github.ref }}
          env-vars-for-codebuild: |
            TEST_TYPE,
            OPERATING_SYSTEM
        env:
          TEST_TYPE: WHEEL
          OPERATING_SYSTEM: ${{ matrix.os }}
